### ISSUE TITLE
Problem to change the orientation on android 

### ISSUE THREAD

**Issue by medreis** [andrea-magni/TFrameStand#15]
Hello,

I'm using to test the WAIT demo, to build and install the application on Android, to perform the rotation of the device the application closes.

I am using delphi Seattle and android 5.

I tested all demo and all closes when o perform the rotation of the device

Thanks

Marcio Eduardo

**Comment by fredycc** [comment]
If I remember correctly, I had to delete: **AndroidManifest.template.xml** and rebuild.

Regards

**Comment by andrea-magni** [comment]
Sometimes when facing this sort of problems, I try to rebuild a new project from scratch (including forms, frames and datamodules). This sometimes solves some strange behavior because all the files needed for app deployment are fresh and up-to-date with latest fix from Embarcadero (according to the Delphi version used).
