### ISSUE TITLE
Main Form Focus Issue

### ISSUE THREAD

**Issue by NEChina** [andrea-magni/TFrameStand#29]
Sorry, my English is bad, mainly rely on Google translation.

TFrameStand v1.3

The problem is the same: https://github.com/andrea-magni/TFrameStand/issues/27

use BUTTON the main form loses focus and can not click on system buttons (minimize, maximize, close).
use TEXT or Image is OK.

The same code:

procedure TFrame1.Button1Click(Sender: TObject);
begin
  FFrame1.Hide();
  FFrame1.Close;
end;

procedure TFrame1.Text1Click(Sender: TObject);
begin
  FFrame1.Hide();
  FFrame1.Close;
end;

**Comment by EndErr** [comment]
You schould try the "wizard" example from demos

**Comment by andrea-magni** [comment]
If you are trying to close the Frame from within the Frame itself, it will cause AV as the Button is likely to have something to do after it has been clicked (thus firing OnClick event).
So you are basically destroying the Frame too early. Use TDelayedAction (FrameStand unit) or switch to some asynchronous communication schema (System.Messaging).

**Comment by EndErr** [comment]
I guess the problem is not described well. I have the same problem too.
The system buttons on the main form (and also the border of the main form that maximizes the form) are not clickable after the a frame is shown. That is after a frame is displayed on the main form (align=Client) and the Frame has at least one button, you can't click the Minimize, Maximize, Close system buttons of the maim form.
