### ISSUE TITLE
Unable to Use Gesture Manager On Windows

### ISSUE THREAD

**Issue by SteveCorbett** [andrea-magni/TFrameStand#31]
When running a Berlin Delphi project on Windows (7) I receive an error  if I assign (at design or runtime) a Gesture Manager to a component.  The error is "Unable to enable or disable IRealTimeStylus: The clear disable flag is set and all clear operations now require physical access"

**Comment by andrea-magni** [comment]
Hi Steve, I never bumped into the problem you are describing but reading here ( https://forums.embarcadero.com/message.jspa?messageID=834476 ) it seems this happens if you add gestures to a control without owner. Are you adding TGestureManager on a frame?
I would suggest to always have the TGestureManager on the main form of the application and use some kind of messaging or other notification mechanism to inform frames about gestures.
This way should avoid all problems.

Sincerely (sorry for the delay)

**Comment by SteveCorbett** [comment]
Hi Andrea, It's been a while since I looked at this issue and worked around it.  Looking back at my code in my Git repository I had the gesture manager as a property of the frame and was assigning the main form's gesture manager to the frame.  Since I was working on a mobile app, I conditioned the assignment not to occur for windows.

Unless someone else comes across this issue I'm happy for you to close this issue.

**Comment by jonahzheng** [comment]
@andrea-magni yes,adding TGestureManager on a frame, will receive an error  "Unable to enable or disable IRealTimeStylus: The clear disable flag is set and all clear operations now require physical access"
as you suggest,  suggest to always have the TGestureManager on the main form of the application.
