### ISSUE TITLE
TVertScrollBox doesn't work properly as a parent of a stand

### ISSUE THREAD

**Issue by jeanvdr** [andrea-magni/TFrameStand#33]
I have some frames containing some editboxes and where the height (of the frame) is superior to the height of the mainform. It is usefull with mobile devices when the user change from a vertical to a horizontal layout.
To see the editboxes on the bottom of the form, I need a vertical scrollbar, using frames without a stand, I can achieve this with a vertscrollbox (client align) on the mainform and the following code:
var
frameBase: TFrame;
begin
framebase := TFrame1.create(self);
frameBase.parent := vertscrollbox1;
frameBase.align := TalignLayout.Horizontal; // otherwise the vertical scroll bar never appears
end;

How can I achieve this with a stand ? Changing the align property of the frame in a stand doesn’t change anything. With the following code, the vertical scrollbar never appears:

frameBase := FrameStand1.New(vertscrollbox1);
frameBase.Frame.align := TAlignLayout.Horizontal;
frameBase.Show();

Thanks

Jean Vandromme

**Comment by azzahrah** [comment]
I have some problem, mybe u can set postiion of frameBase

**Comment by andrea-magni** [comment]
Hi @jeanvdr and @azzahrah , sorry for the late...
You can see at these lines: 
- FrameStand.pas, 549 (https://github.com/andrea-magni/TFrameStand/blob/e92ab6725f6de50f91ce3a11c3bca83303959600/source/FrameStand.pas#L549)
- FrameStand.pas, 556 (https://github.com/andrea-magni/TFrameStand/blob/e92ab6725f6de50f91ce3a11c3bca83303959600/source/FrameStand.pas#L556)

That the Stand gets its Align property set to Contents (on Delphi versions equal or later than 10.1 Berlin. This is because since then there some weird behavior in the Style Designer or in the RTL (I have not delved into this very much honestly) causing the Align property to be reset to Center.

As a workaround for your problem, I'd try to override the Align property's value right after showing the framestand (use an AfterShow method or and OnAfterShow event handler).

Please let me know if this solves your issue and feel free to reopen this issue or comment.

Sincerely,
Andrea

**Comment by vrobidet** [comment]
Hi, 

I have the same problem with tvertscrollbox in frame.
The vertical scrollbar never appears.

If I use directly with Tframe, the vertical scrollbar appears.

I have modified Align property after show but that doesn't solve the problem.

Delphi 10.4.2

Thanks

Vincent

**Comment by vrobidet** [comment]
Hi, 

Since I put a TCombobox on the parent form, the problem is solved 
but I don't know why at the moment.

Vincent
