### ISSUE TITLE
Sheet Dialog Implementation

### ISSUE THREAD

**Issue by azzahrah** [andrea-magni/TFrameStand#34]
Howto implementation sheet expandable like this:

(https://camo.githubusercontent.com/a9c746f6132ccdb741e82de015806abd21701ccf/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f385a474e722e676966)

**Comment by andrea-magni** [comment]
Hi, sorry for the late, I was in vacation ;-)

I just pushed a new demo (BottomSheet). It is still a bit raw but should serve as idea.

Commit: https://github.com/andrea-magni/TFrameStand/commit/1876940c96ab4a28ec55f01c3a1a1d4982d8204e

Let me know what you think about it

**Comment by azzahrah** [comment]
Hi,

Thank you for help, i just try demo, very inspired me....

**Comment by andrea-magni** [comment]
Hi, I just pushed some improvements. Now you have to grab the Peek rectangle in order to activate the gesture (making it more usable especially if you have controls inside the inner frame).
Also added a post to my blog with a short video: https://blog.andreamagni.eu/2018/04/tframestand-new-bottomsheet-demo/

Several improvements can be made (for example to completely hide the Peek rectangle or to set a maximum width for the bottom sheet) but obviously it depends on your use case.

Bye

**Comment by azzahrah** [comment]
Hi Andrea,
Very nice improvement, but is possible to place TMapView in main form?

**Comment by azzahrah** [comment]
Hi,
The trick you used I have done, and it works, but I have to hide TMapview if want to display the a frame, and display TMapView if the frame is hidden, yes TMapView doesnot have Z-Order so its impossible to place another component top of TMapView

**Comment by andrea-magni** [comment]
In the newly published Embarcadero Roadmap there is a "Android Z-Order (native windowing)" entry that looks promising for the issue with TMapView... Finger crossing ;-)
https://community.embarcadero.com/article/news/16638-rad-studio-august-2018-roadmap
