### ISSUE TITLE
"Close" problem

### ISSUE THREAD

**Issue by DAppx** [andrea-magni/TFrameStand#6]
hi .
in demo ViewAndDialogsStandframe .
update

function TMainForm.GetRatingDialogInfo: TFrameInfo<TRatingDialogFrame>;
begin
  if not Assigned(FRatingDialogInfo) then
  begin
    FRatingDialogInfo := FrameStand1.New<TRatingDialogFrame>(ListView1);

    FRatingDialogInfo.Frame.OnRatingChanged :=
      procedure (ARating: Integer)
      begin
        ShowMessage('Rated: ' + ARating.ToString);
        FRatingDialogInfo.Hide();
      end;

    FRatingDialogInfo.Frame.OnCancel :=
      procedure
      begin
        //ShowMessage('Rating cancelled!');
     //   FRatingDialogInfo.Hide();
        FRatingDialogInfo.Close(); //add
        FRatingDialogInfo := nil  ;  //add 
      end;

  end;
 when click  i'v got Access violation error !

i want to close and free FRatingDialogInfo 

can you tell me the right way to  close and free FRatingDialogInfo  in OnCancel

thanks

**Comment by DAppx** [comment]
i watch #29 TFrameStand Deep Dive: Build Visually Stunning and Consistent UI/UX with FMX Frames

i update Frames.RatingDialog   in  Deep Dive Demo 

 private
    [FrameInfo] FInfo:TframeInfo<TRatingDialogFrame> ;

procedure TRatingDialogFrame.CancelButtonClick(Sender: TObject);
begin
  if Assigned(OnCancel) then
    OnCancel();
  FInfo.hide;
  FInfo.close;

end;

    [weak] FRatingDialogInfo: TFrameInfo<TRatingDialogFrame>;

    FRatingDialogInfo.Frame.OnCancel :=
      procedure
      begin
        FRatingDialogInfo := nil  ;
       // self.SetFocused(self.ListView1);
      end;

Access violation error is OK .

I  find in 32bit windows  when use frameinfo.close 
mainform can not drag , must click mainform client . it can drag  .

**Comment by andrea-magni** [comment]
Hi, the proper way to handle closing of a framestand should look like this:

    FRatingDialogInfo.Frame.OnCancel :=
      procedure
      begin
        ShowMessage('Rating cancelled!');
        FRatingDialogInfo.Hide(0,
          procedure
          begin
            FRatingDialogInfo.Close();
            FRatingDialogInfo := nil;
          end
        );
      end;

That is passing the anonymous method to the Hide method, in order to Close (and set FRatingDialogInfo to nil) only once the framestand has finished hiding.
Please consider that in this example, I set up a "singleton" instance in order to avoid continuos creation/destroy of the framestand... so if you need the opposite, I would suggest to simply get rid of the singleton...

About the mainform drag problem, can you provide further details, please?

HTH
