### ISSUE TITLE
Incompatible types: 'System.SysUtils.TProc<SubjectStand.TSubjectInfo>' and 'Procedure'

### ISSUE THREAD

**Issue by rioda78** [andrea-magni/TFrameStand#63]
environment
windows 10
delphi 10.4.2

when try run dialogproject.dpr and helloworldproject.dpr from demo folder, i get error 
[dcc32 Error] `Forms.Main.pas(99):` E2010 Incompatible types: 'System.SysUtils.TProc<SubjectStand.TSubjectInfo>' and procedure

 `  FrameStand1.CommonActions.Add('*_cancel'
  , procedure (AInfo: TFrameInfo<TFrame>)
    begin
      if (AInfo.Frame is TColorDialogFrame) then
        TColorDialogFrame(AInfo.Frame).Cancel;
    end
  );`
and code 
`  FrameStand1.CommonActions.Add(
    'SayHello*'
    , procedure (AInfo: TFrameInfo<TFrame>)
      begin
        ShowMessage('Hello, the frame is ' + AInfo.Frame.ClassName);
      end
  );`
thanks very much for this project

**Comment by andrea-magni** [comment]
Hi, at some point I refactored some functionalities in order to share them across TFrameStand and TFormStand.
TSubjectStand is the common ancestor of the two.
The demo may be lagging behind, thanks for pointing this out.

Just substitute TFrameInfo with TSubjectInfo (add SubjectStand unit to the uses clause if not already threre) and it should work. Then, you can cast AInfo to TFrameInfo or cast AInfo.Subject to TFrame, as you like.

Thanks for the kind words about the project.

Sincerely
